### ISSUE TITLE
On notion: find the list of our values - everyone should choose one, come up with an example of that value and add it to this github issue

### ISSUE THREAD

**Issue by dalilab** [dali-lab/release-the-llama#18]

**Comment by ykim5200** [comment]
We adapt: There’s no recipe - be ready and willing to change course and iterate. Example: we're literally doing this remotely right now.

**Comment by shreyas-v-agnihotri** [comment]
3. We believe that difference is a strength: We're combining designers, devs, and PMs from all different majors together to complete this task.

**Comment by emmawagner21** [comment]
7. We risk being genuine and vulnerable: Admit weakness, ask questions, be open when asking for and giving help, trusting others and yourself.

**Comment by drewschneider17** [comment]
8. Code, laugh, love: Don’t take life too seriously--  Our task right now is to "release the llama". Although we are learning throughout the process, we are having fun and not taking ourselves too seriously. We have fun lol

**Comment by ghost** [comment]
We invest in each other: Be generous with your time, knowledge, and emotional support. Learn from your teammates and give back through mentorship.

Example: We started our Zoom meeting by all checking in on each other—emotional support is important right now!

**Comment by thanvinhbaohoang** [comment]
1.We step up: Meet challenges, pursue learning opportunities, choose to take initiative in big and small ways.

**Comment by tvergho** [comment]
We "code, laugh, love" – we started this Zoom meeting by playing "rescue the llama."

**Comment by Vi-N-Tran** [comment]
Code, laugh, love: Team/Lab social outside of work :)

**Comment by hannahutter** [comment]
7. We risk being genuine and vulnerable: we ask for help when we need it

**Comment by jeffzyliu** [comment]
8. **Code, Laugh, Love**: Don't take life too seriously.

Whee we are freeing a llama, how fun and non-serious :3.

**Comment by christinabschoeller** [comment]
We are tenacious: we find creative solutions in unprecedented times

**Comment by LucCote** [comment]
1. **We step up**: Meet challenges, pursue learning opportunities, choose to take initiative in big and small ways.
We started off the meeting with some members steeping up and starting to organize and break down the challenge

**Comment by jenniferyxu** [comment]
8) Code, laugh, love: Don’t take life too seriously. 

We have fun bonding as a team :)

**Comment by juliakern-dali** [comment]
4. We adapt. 
We are learning how to do onboarding over zoom.

**Comment by sathvi-k** [comment]
4. **We adapt:** go with the **flow** !! sometimes things don't turn out the way you hope so be ready to change course

**Comment by michael-h-lin-21** [comment]
6. **We invest in each **other:****: Spending time with teammates during team bonding events to understand how everyone is doing. Share insights and past experience

**Comment by irenelam22** [comment]
3. We believe that difference is a strength -- diversity and inclusivity, accept our differences to produce something greater than the sum of our parts :)

**Comment by samihadatta** [comment]
**5. We create thoughtfully**: Investigate the value and consequences of what, how, and why we make. Set a high bar, technically and ethically. --> we design/code/PM in ways that rival machines but we ourselves are not machines and think about what we're doing
